# Generated by Django 6.0.3 on 2026-03-10 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='회사명')),
                ('business_number', models.CharField(max_length=20, verbose_name='사업자등록번호')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='광고비 잔액')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advertiser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '광고주',
                'verbose_name_plural': '광고주 목록',
            },
        ),
    ]
