# Generated by Django 6.0.3 on 2026-03-10 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='지면명')),
                ('slot_code', models.SlugField(unique=True, verbose_name='슬롯 코드')),
                ('width', models.IntegerField(verbose_name='너비(px)')),
                ('height', models.IntegerField(verbose_name='높이(px)')),
                ('media_type', models.CharField(choices=[('web', '웹'), ('mobile', '모바일'), ('video', '동영상'), ('inapp', '인앱')], default='web', max_length=10, verbose_name='매체 유형')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
            ],
            options={
                'verbose_name': '인벤토리(지면)',
                'verbose_name_plural': '인벤토리(지면) 목록',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='캠페인명')),
                ('status', models.CharField(choices=[('draft', '초안'), ('active', '활성'), ('paused', '일시정지'), ('completed', '완료')], default='draft', max_length=20, verbose_name='상태')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='총 예산')),
                ('daily_budget', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='일일 예산')),
                ('start_date', models.DateTimeField(verbose_name='시작일')),
                ('end_date', models.DateTimeField(verbose_name='종료일')),
                ('target_impressions', models.IntegerField(default=0, verbose_name='목표 노출수')),
                ('billing_type', models.CharField(choices=[('cpm', 'CPM (1,000회 노출당 과금)'), ('cpc', 'CPC (클릭당 과금)'), ('cpp', 'CPP (기간당 고정)'), ('cpv', 'CPV (동영상 조회당 과금)')], default='cpm', max_length=10, verbose_name='과금 방식')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='단가')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='accounts.advertiser', verbose_name='광고주')),
            ],
            options={
                'verbose_name': '캠페인',
                'verbose_name_plural': '캠페인 목록',
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='광고명')),
                ('status', models.CharField(choices=[('active', '활성'), ('paused', '일시정지'), ('ended', '종료')], default='active', max_length=20, verbose_name='상태')),
                ('weight', models.IntegerField(default=100, verbose_name='노출 가중치(1~100)')),
                ('frequency_cap', models.IntegerField(blank=True, null=True, verbose_name='빈도 제한(일 기준)')),
                ('targeting', models.JSONField(blank=True, default=dict, verbose_name='타겟팅 설정')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='campaigns.campaign', verbose_name='캠페인')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='campaigns.inventory', verbose_name='타겟 지면')),
            ],
            options={
                'verbose_name': '광고',
                'verbose_name_plural': '광고 목록',
            },
        ),
        migrations.CreateModel(
            name='Creative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='creatives/%Y/%m/', verbose_name='소재 파일')),
                ('click_url', models.URLField(verbose_name='클릭 URL')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='대체 텍스트')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatives', to='campaigns.ad', verbose_name='광고')),
            ],
            options={
                'verbose_name': '소재',
                'verbose_name_plural': '소재 목록',
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status', 'start_date', 'end_date'], name='campaigns_c_status_8f4ce1_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['status'], name='campaigns_a_status_a190ec_idx'),
        ),
    ]
