# Generated by Django 6.0.3 on 2026-03-10 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='집계 날짜')),
                ('impressions', models.IntegerField(default=0, verbose_name='노출수')),
                ('clicks', models.IntegerField(default=0, verbose_name='클릭수')),
                ('ctr', models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='CTR')),
                ('spent', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='소진 광고비')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='campaigns.ad', verbose_name='광고')),
            ],
            options={
                'verbose_name': '일별 통계',
                'verbose_name_plural': '일별 통계 목록',
                'indexes': [models.Index(fields=['ad', 'date'], name='reports_dai_ad_id_d5d9f5_idx')],
                'unique_together': {('ad', 'date')},
            },
        ),
    ]
