# Generated by Django 6.0.3 on 2026-03-10 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('impression', '노출'), ('click', '클릭')], max_length=20, verbose_name='이벤트 유형')),
                ('ip_address', models.GenericIPAddressField(verbose_name='사용자 IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('device_type', models.CharField(choices=[('pc', 'PC'), ('mobile', '모바일'), ('tablet', '태블릿')], default='pc', max_length=10, verbose_name='디바이스')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='이벤트 발생 시각')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='campaigns.ad', verbose_name='광고')),
            ],
            options={
                'verbose_name': '이벤트 로그',
                'verbose_name_plural': '이벤트 로그 목록',
                'indexes': [models.Index(fields=['ad', 'event_type', 'created_at'], name='serving_eve_ad_id_64f90a_idx'), models.Index(fields=['ip_address', 'ad'], name='serving_eve_ip_addr_a5948e_idx')],
            },
        ),
    ]
