# Generated by Django 6.0.3 on 2026-03-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('serving', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['created_at'], name='serving_eve_created_7aed9e_idx'),
        ),
    ]
